// <auto-generated />
using System;
using DataBase.GameDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DB.Data.Migrations.GameMigrations
{
    [DbContext(typeof(GameDBContext))]
    partial class GameDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DB.Data.GameDB.Character", b =>
                {
                    b.Property<long>("characterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("charactetType")
                        .HasColumnType("int");

                    b.Property<DateTime>("createTime")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("userId")
                        .HasColumnType("bigint");

                    b.HasKey("characterId");

                    b.HasIndex(new[] { "userId" }, "IX_CHARACTER_USER_ID");

                    b.ToTable("character");
                });

            modelBuilder.Entity("DataBase.GameDB.UserInfo", b =>
                {
                    b.Property<long>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("accountId")
                        .HasColumnType("bigint");

                    b.Property<string>("nickName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("userId");

                    b.HasIndex(new[] { "accountId" }, "IX_USER_INFO_ACCOUNT_ID");

                    b.ToTable("userInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
